### ISSUE TITLE
Can't publish the views

### ISSUE THREAD

**Issue by AbdelElrafa** [lilessam/TranslationMan#2]
Hey this command doesn't work - php artisan vendor:publish --provider=Lilessam\Translationman\TranslationmanServiceProvider

After running it I get a Publishing complete message but it doesn't work.

**Comment by AhmedEssamElNaggar** [comment]
The service provider needs to be placed in quotes like this
`php artisan vendor:publish --provider="Lilessam\Translationman\TranslationmanServiceProvider"`
